/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as PublicRouteImport } from './routes/_public/route'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as PublicIndexImport } from './routes/_public/index'
import { Route as errors503Import } from './routes/(errors)/503'
import { Route as errors500Import } from './routes/(errors)/500'
import { Route as errors404Import } from './routes/(errors)/404'
import { Route as errors403Import } from './routes/(errors)/403'
import { Route as errors401Import } from './routes/(errors)/401'
import { Route as authSignUpImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2Import } from './routes/(auth)/sign-in-2'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authSetpasswordImport } from './routes/(auth)/setpassword'
import { Route as authRegisterImport } from './routes/(auth)/register'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings/route'
import { Route as AdminUsersIndexImport } from './routes/admin/users/index'
import { Route as AdminTasksIndexImport } from './routes/admin/tasks/index'
import { Route as AdminSettingsIndexImport } from './routes/admin/settings/index'
import { Route as AdminProductsIndexImport } from './routes/admin/products/index'
import { Route as AdminOrderIndexImport } from './routes/admin/order/index'
import { Route as AdminHelpCenterIndexImport } from './routes/admin/help-center/index'
import { Route as AdminContactIndexImport } from './routes/admin/contact/index'
import { Route as AdminChatsIndexImport } from './routes/admin/chats/index'
import { Route as AdminAppsIndexImport } from './routes/admin/apps/index'
import { Route as PublicTermsIndexImport } from './routes/_public/terms/index'
import { Route as PublicProductsIndexImport } from './routes/_public/products/index'
import { Route as PublicPrivacyPolicyIndexImport } from './routes/_public/privacy-policy/index'
import { Route as PublicContactIndexImport } from './routes/_public/contact/index'
import { Route as PublicBrandGuidelinesIndexImport } from './routes/_public/brand-guidelines/index'
import { Route as PublicAboutIndexImport } from './routes/_public/about/index'
import { Route as AdminSettingsNotificationsImport } from './routes/admin/settings/notifications'
import { Route as AdminSettingsDisplayImport } from './routes/admin/settings/display'
import { Route as AdminSettingsAppearanceImport } from './routes/admin/settings/appearance'
import { Route as AdminSettingsAccountImport } from './routes/admin/settings/account'
import { Route as AdminProductsUpdateIndexImport } from './routes/admin/products/update/index'
import { Route as AdminProductsAddIndexImport } from './routes/admin/products/add/index'
import { Route as PublicProductsCategoryIndexImport } from './routes/_public/products/$category/index'
import { Route as PublicProductsCategoryIdIndexImport } from './routes/_public/products/$category/$id/index'

// Create/Update Routes

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const PublicRouteRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const PublicIndexRoute = PublicIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)

const errors503Route = errors503Import.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRoute,
} as any)

const errors500Route = errors500Import.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const errors404Route = errors404Import.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const errors403Route = errors403Import.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRoute,
} as any)

const errors401Route = errors401Import.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const authSignIn2Route = authSignIn2Import.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authSetpasswordRoute = authSetpasswordImport.update({
  id: '/(auth)/setpassword',
  path: '/setpassword',
  getParentRoute: () => rootRoute,
} as any)

const authRegisterRoute = authRegisterImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const AdminSettingsRouteRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminUsersIndexRoute = AdminUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminTasksIndexRoute = AdminTasksIndexImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminSettingsIndexRoute = AdminSettingsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)

const AdminProductsIndexRoute = AdminProductsIndexImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminOrderIndexRoute = AdminOrderIndexImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminHelpCenterIndexRoute = AdminHelpCenterIndexImport.update({
  id: '/help-center/',
  path: '/help-center/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminContactIndexRoute = AdminContactIndexImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminChatsIndexRoute = AdminChatsIndexImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminAppsIndexRoute = AdminAppsIndexImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const PublicTermsIndexRoute = PublicTermsIndexImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => PublicRouteRoute,
} as any)

const PublicProductsIndexRoute = PublicProductsIndexImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PublicRouteRoute,
} as any)

const PublicPrivacyPolicyIndexRoute = PublicPrivacyPolicyIndexImport.update({
  id: '/privacy-policy/',
  path: '/privacy-policy/',
  getParentRoute: () => PublicRouteRoute,
} as any)

const PublicContactIndexRoute = PublicContactIndexImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => PublicRouteRoute,
} as any)

const PublicBrandGuidelinesIndexRoute = PublicBrandGuidelinesIndexImport.update(
  {
    id: '/brand-guidelines/',
    path: '/brand-guidelines/',
    getParentRoute: () => PublicRouteRoute,
  } as any,
)

const PublicAboutIndexRoute = PublicAboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => PublicRouteRoute,
} as any)

const AdminSettingsNotificationsRoute = AdminSettingsNotificationsImport.update(
  {
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any,
)

const AdminSettingsDisplayRoute = AdminSettingsDisplayImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)

const AdminSettingsAppearanceRoute = AdminSettingsAppearanceImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)

const AdminSettingsAccountRoute = AdminSettingsAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)

const AdminProductsUpdateIndexRoute = AdminProductsUpdateIndexImport.update({
  id: '/products/update/',
  path: '/products/update/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminProductsAddIndexRoute = AdminProductsAddIndexImport.update({
  id: '/products/add/',
  path: '/products/add/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const PublicProductsCategoryIndexRoute =
  PublicProductsCategoryIndexImport.update({
    id: '/products/$category/',
    path: '/products/$category/',
    getParentRoute: () => PublicRouteRoute,
  } as any)

const PublicProductsCategoryIdIndexRoute =
  PublicProductsCategoryIdIndexImport.update({
    id: '/products/$category/$id/',
    path: '/products/$category/$id/',
    getParentRoute: () => PublicRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/setpassword': {
      id: '/(auth)/setpassword'
      path: '/setpassword'
      fullPath: '/setpassword'
      preLoaderRoute: typeof authSetpasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503Import
      parentRoute: typeof rootRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexImport
      parentRoute: typeof PublicRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/settings/account': {
      id: '/admin/settings/account'
      path: '/account'
      fullPath: '/admin/settings/account'
      preLoaderRoute: typeof AdminSettingsAccountImport
      parentRoute: typeof AdminSettingsRouteImport
    }
    '/admin/settings/appearance': {
      id: '/admin/settings/appearance'
      path: '/appearance'
      fullPath: '/admin/settings/appearance'
      preLoaderRoute: typeof AdminSettingsAppearanceImport
      parentRoute: typeof AdminSettingsRouteImport
    }
    '/admin/settings/display': {
      id: '/admin/settings/display'
      path: '/display'
      fullPath: '/admin/settings/display'
      preLoaderRoute: typeof AdminSettingsDisplayImport
      parentRoute: typeof AdminSettingsRouteImport
    }
    '/admin/settings/notifications': {
      id: '/admin/settings/notifications'
      path: '/notifications'
      fullPath: '/admin/settings/notifications'
      preLoaderRoute: typeof AdminSettingsNotificationsImport
      parentRoute: typeof AdminSettingsRouteImport
    }
    '/_public/about/': {
      id: '/_public/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutIndexImport
      parentRoute: typeof PublicRouteImport
    }
    '/_public/brand-guidelines/': {
      id: '/_public/brand-guidelines/'
      path: '/brand-guidelines'
      fullPath: '/brand-guidelines'
      preLoaderRoute: typeof PublicBrandGuidelinesIndexImport
      parentRoute: typeof PublicRouteImport
    }
    '/_public/contact/': {
      id: '/_public/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactIndexImport
      parentRoute: typeof PublicRouteImport
    }
    '/_public/privacy-policy/': {
      id: '/_public/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PublicPrivacyPolicyIndexImport
      parentRoute: typeof PublicRouteImport
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PublicProductsIndexImport
      parentRoute: typeof PublicRouteImport
    }
    '/_public/terms/': {
      id: '/_public/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsIndexImport
      parentRoute: typeof PublicRouteImport
    }
    '/admin/apps/': {
      id: '/admin/apps/'
      path: '/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof AdminAppsIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/chats/': {
      id: '/admin/chats/'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminChatsIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/contact/': {
      id: '/admin/contact/'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/help-center/': {
      id: '/admin/help-center/'
      path: '/help-center'
      fullPath: '/admin/help-center'
      preLoaderRoute: typeof AdminHelpCenterIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/order/': {
      id: '/admin/order/'
      path: '/order'
      fullPath: '/admin/order'
      preLoaderRoute: typeof AdminOrderIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexImport
      parentRoute: typeof AdminSettingsRouteImport
    }
    '/admin/tasks/': {
      id: '/admin/tasks/'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/_public/products/$category/': {
      id: '/_public/products/$category/'
      path: '/products/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof PublicProductsCategoryIndexImport
      parentRoute: typeof PublicRouteImport
    }
    '/admin/products/add/': {
      id: '/admin/products/add/'
      path: '/products/add'
      fullPath: '/admin/products/add'
      preLoaderRoute: typeof AdminProductsAddIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/products/update/': {
      id: '/admin/products/update/'
      path: '/products/update'
      fullPath: '/admin/products/update'
      preLoaderRoute: typeof AdminProductsUpdateIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/_public/products/$category/$id/': {
      id: '/_public/products/$category/$id/'
      path: '/products/$category/$id'
      fullPath: '/products/$category/$id'
      preLoaderRoute: typeof PublicProductsCategoryIdIndexImport
      parentRoute: typeof PublicRouteImport
    }
  }
}

// Create and export the route tree

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAboutIndexRoute: typeof PublicAboutIndexRoute
  PublicBrandGuidelinesIndexRoute: typeof PublicBrandGuidelinesIndexRoute
  PublicContactIndexRoute: typeof PublicContactIndexRoute
  PublicPrivacyPolicyIndexRoute: typeof PublicPrivacyPolicyIndexRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
  PublicTermsIndexRoute: typeof PublicTermsIndexRoute
  PublicProductsCategoryIndexRoute: typeof PublicProductsCategoryIndexRoute
  PublicProductsCategoryIdIndexRoute: typeof PublicProductsCategoryIdIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicAboutIndexRoute: PublicAboutIndexRoute,
  PublicBrandGuidelinesIndexRoute: PublicBrandGuidelinesIndexRoute,
  PublicContactIndexRoute: PublicContactIndexRoute,
  PublicPrivacyPolicyIndexRoute: PublicPrivacyPolicyIndexRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
  PublicTermsIndexRoute: PublicTermsIndexRoute,
  PublicProductsCategoryIndexRoute: PublicProductsCategoryIndexRoute,
  PublicProductsCategoryIdIndexRoute: PublicProductsCategoryIdIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminSettingsRouteRouteChildren {
  AdminSettingsAccountRoute: typeof AdminSettingsAccountRoute
  AdminSettingsAppearanceRoute: typeof AdminSettingsAppearanceRoute
  AdminSettingsDisplayRoute: typeof AdminSettingsDisplayRoute
  AdminSettingsNotificationsRoute: typeof AdminSettingsNotificationsRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsAccountRoute: AdminSettingsAccountRoute,
  AdminSettingsAppearanceRoute: AdminSettingsAppearanceRoute,
  AdminSettingsDisplayRoute: AdminSettingsDisplayRoute,
  AdminSettingsNotificationsRoute: AdminSettingsNotificationsRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAppsIndexRoute: typeof AdminAppsIndexRoute
  AdminChatsIndexRoute: typeof AdminChatsIndexRoute
  AdminContactIndexRoute: typeof AdminContactIndexRoute
  AdminHelpCenterIndexRoute: typeof AdminHelpCenterIndexRoute
  AdminOrderIndexRoute: typeof AdminOrderIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminProductsAddIndexRoute: typeof AdminProductsAddIndexRoute
  AdminProductsUpdateIndexRoute: typeof AdminProductsUpdateIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminAppsIndexRoute: AdminAppsIndexRoute,
  AdminChatsIndexRoute: AdminChatsIndexRoute,
  AdminContactIndexRoute: AdminContactIndexRoute,
  AdminHelpCenterIndexRoute: AdminHelpCenterIndexRoute,
  AdminOrderIndexRoute: AdminOrderIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminProductsAddIndexRoute: AdminProductsAddIndexRoute,
  AdminProductsUpdateIndexRoute: AdminProductsUpdateIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/register': typeof authRegisterRoute
  '/setpassword': typeof authSetpasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/display': typeof AdminSettingsDisplayRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/about': typeof PublicAboutIndexRoute
  '/brand-guidelines': typeof PublicBrandGuidelinesIndexRoute
  '/contact': typeof PublicContactIndexRoute
  '/privacy-policy': typeof PublicPrivacyPolicyIndexRoute
  '/products': typeof PublicProductsIndexRoute
  '/terms': typeof PublicTermsIndexRoute
  '/admin/apps': typeof AdminAppsIndexRoute
  '/admin/chats': typeof AdminChatsIndexRoute
  '/admin/contact': typeof AdminContactIndexRoute
  '/admin/help-center': typeof AdminHelpCenterIndexRoute
  '/admin/order': typeof AdminOrderIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/products/$category': typeof PublicProductsCategoryIndexRoute
  '/admin/products/add': typeof AdminProductsAddIndexRoute
  '/admin/products/update': typeof AdminProductsUpdateIndexRoute
  '/products/$category/$id': typeof PublicProductsCategoryIdIndexRoute
}

export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/register': typeof authRegisterRoute
  '/setpassword': typeof authSetpasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/display': typeof AdminSettingsDisplayRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/about': typeof PublicAboutIndexRoute
  '/brand-guidelines': typeof PublicBrandGuidelinesIndexRoute
  '/contact': typeof PublicContactIndexRoute
  '/privacy-policy': typeof PublicPrivacyPolicyIndexRoute
  '/products': typeof PublicProductsIndexRoute
  '/terms': typeof PublicTermsIndexRoute
  '/admin/apps': typeof AdminAppsIndexRoute
  '/admin/chats': typeof AdminChatsIndexRoute
  '/admin/contact': typeof AdminContactIndexRoute
  '/admin/help-center': typeof AdminHelpCenterIndexRoute
  '/admin/order': typeof AdminOrderIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/products/$category': typeof PublicProductsCategoryIndexRoute
  '/admin/products/add': typeof AdminProductsAddIndexRoute
  '/admin/products/update': typeof AdminProductsUpdateIndexRoute
  '/products/$category/$id': typeof PublicProductsCategoryIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/setpassword': typeof authSetpasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/display': typeof AdminSettingsDisplayRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/_public/about/': typeof PublicAboutIndexRoute
  '/_public/brand-guidelines/': typeof PublicBrandGuidelinesIndexRoute
  '/_public/contact/': typeof PublicContactIndexRoute
  '/_public/privacy-policy/': typeof PublicPrivacyPolicyIndexRoute
  '/_public/products/': typeof PublicProductsIndexRoute
  '/_public/terms/': typeof PublicTermsIndexRoute
  '/admin/apps/': typeof AdminAppsIndexRoute
  '/admin/chats/': typeof AdminChatsIndexRoute
  '/admin/contact/': typeof AdminContactIndexRoute
  '/admin/help-center/': typeof AdminHelpCenterIndexRoute
  '/admin/order/': typeof AdminOrderIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_public/products/$category/': typeof PublicProductsCategoryIndexRoute
  '/admin/products/add/': typeof AdminProductsAddIndexRoute
  '/admin/products/update/': typeof AdminProductsUpdateIndexRoute
  '/_public/products/$category/$id/': typeof PublicProductsCategoryIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/admin'
    | '/admin/settings'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/register'
    | '/setpassword'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/admin/'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/notifications'
    | '/about'
    | '/brand-guidelines'
    | '/contact'
    | '/privacy-policy'
    | '/products'
    | '/terms'
    | '/admin/apps'
    | '/admin/chats'
    | '/admin/contact'
    | '/admin/help-center'
    | '/admin/order'
    | '/admin/products'
    | '/admin/settings/'
    | '/admin/tasks'
    | '/admin/users'
    | '/products/$category'
    | '/admin/products/add'
    | '/admin/products/update'
    | '/products/$category/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/register'
    | '/setpassword'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/admin'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/notifications'
    | '/about'
    | '/brand-guidelines'
    | '/contact'
    | '/privacy-policy'
    | '/products'
    | '/terms'
    | '/admin/apps'
    | '/admin/chats'
    | '/admin/contact'
    | '/admin/help-center'
    | '/admin/order'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/users'
    | '/products/$category'
    | '/admin/products/add'
    | '/admin/products/update'
    | '/products/$category/$id'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/admin/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/otp'
    | '/(auth)/register'
    | '/(auth)/setpassword'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_public/'
    | '/admin/'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/notifications'
    | '/_public/about/'
    | '/_public/brand-guidelines/'
    | '/_public/contact/'
    | '/_public/privacy-policy/'
    | '/_public/products/'
    | '/_public/terms/'
    | '/admin/apps/'
    | '/admin/chats/'
    | '/admin/contact/'
    | '/admin/help-center/'
    | '/admin/order/'
    | '/admin/products/'
    | '/admin/settings/'
    | '/admin/tasks/'
    | '/admin/users/'
    | '/_public/products/$category/'
    | '/admin/products/add/'
    | '/admin/products/update/'
    | '/_public/products/$category/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authOtpRoute: typeof authOtpRoute
  authRegisterRoute: typeof authRegisterRoute
  authSetpasswordRoute: typeof authSetpasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authOtpRoute: authOtpRoute,
  authRegisterRoute: authRegisterRoute,
  authSetpasswordRoute: authSetpasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_public",
        "/admin",
        "/(auth)/forgot-password",
        "/(auth)/login",
        "/(auth)/otp",
        "/(auth)/register",
        "/(auth)/setpassword",
        "/(auth)/sign-in",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/_public": {
      "filePath": "_public/route.tsx",
      "children": [
        "/_public/",
        "/_public/about/",
        "/_public/brand-guidelines/",
        "/_public/contact/",
        "/_public/privacy-policy/",
        "/_public/products/",
        "/_public/terms/",
        "/_public/products/$category/",
        "/_public/products/$category/$id/"
      ]
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/settings",
        "/admin/",
        "/admin/apps/",
        "/admin/chats/",
        "/admin/contact/",
        "/admin/help-center/",
        "/admin/order/",
        "/admin/products/",
        "/admin/tasks/",
        "/admin/users/",
        "/admin/products/add/",
        "/admin/products/update/"
      ]
    },
    "/admin/settings": {
      "filePath": "admin/settings/route.tsx",
      "parent": "/admin",
      "children": [
        "/admin/settings/account",
        "/admin/settings/appearance",
        "/admin/settings/display",
        "/admin/settings/notifications",
        "/admin/settings/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/register": {
      "filePath": "(auth)/register.tsx"
    },
    "/(auth)/setpassword": {
      "filePath": "(auth)/setpassword.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.tsx"
    },
    "/_public/": {
      "filePath": "_public/index.tsx",
      "parent": "/_public"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/admin/settings/account": {
      "filePath": "admin/settings/account.tsx",
      "parent": "/admin/settings"
    },
    "/admin/settings/appearance": {
      "filePath": "admin/settings/appearance.tsx",
      "parent": "/admin/settings"
    },
    "/admin/settings/display": {
      "filePath": "admin/settings/display.tsx",
      "parent": "/admin/settings"
    },
    "/admin/settings/notifications": {
      "filePath": "admin/settings/notifications.tsx",
      "parent": "/admin/settings"
    },
    "/_public/about/": {
      "filePath": "_public/about/index.tsx",
      "parent": "/_public"
    },
    "/_public/brand-guidelines/": {
      "filePath": "_public/brand-guidelines/index.tsx",
      "parent": "/_public"
    },
    "/_public/contact/": {
      "filePath": "_public/contact/index.tsx",
      "parent": "/_public"
    },
    "/_public/privacy-policy/": {
      "filePath": "_public/privacy-policy/index.tsx",
      "parent": "/_public"
    },
    "/_public/products/": {
      "filePath": "_public/products/index.tsx",
      "parent": "/_public"
    },
    "/_public/terms/": {
      "filePath": "_public/terms/index.tsx",
      "parent": "/_public"
    },
    "/admin/apps/": {
      "filePath": "admin/apps/index.tsx",
      "parent": "/admin"
    },
    "/admin/chats/": {
      "filePath": "admin/chats/index.tsx",
      "parent": "/admin"
    },
    "/admin/contact/": {
      "filePath": "admin/contact/index.tsx",
      "parent": "/admin"
    },
    "/admin/help-center/": {
      "filePath": "admin/help-center/index.tsx",
      "parent": "/admin"
    },
    "/admin/order/": {
      "filePath": "admin/order/index.tsx",
      "parent": "/admin"
    },
    "/admin/products/": {
      "filePath": "admin/products/index.tsx",
      "parent": "/admin"
    },
    "/admin/settings/": {
      "filePath": "admin/settings/index.tsx",
      "parent": "/admin/settings"
    },
    "/admin/tasks/": {
      "filePath": "admin/tasks/index.tsx",
      "parent": "/admin"
    },
    "/admin/users/": {
      "filePath": "admin/users/index.tsx",
      "parent": "/admin"
    },
    "/_public/products/$category/": {
      "filePath": "_public/products/$category/index.tsx",
      "parent": "/_public"
    },
    "/admin/products/add/": {
      "filePath": "admin/products/add/index.tsx",
      "parent": "/admin"
    },
    "/admin/products/update/": {
      "filePath": "admin/products/update/index.tsx",
      "parent": "/admin"
    },
    "/_public/products/$category/$id/": {
      "filePath": "_public/products/$category/$id/index.tsx",
      "parent": "/_public"
    }
  }
}
ROUTE_MANIFEST_END */
